sonar.projectKey=ShelfLink
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=sqp_8c258ebb87bd5f1e3c95a0363cca270dfa9b4802
sonar.php.coverage.reportPaths=coverage.xml
# Exclude vendor folder to keep reports clean
sonar.exclusions=vendor/**
